FROM nodered/node-red-docker:rpi
RUN npm install node-red-contrib-hueplus
RUN npm install node-red-contrib-influxdb
RUN npm install node-red-dashboard
RUN npm install node-red-node-mysql
RUN npm install node-red-node-wemo
